# Generated by Django 5.1.15 on 2026-06-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonnote',
            name='client',
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='tpms_client_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
