# Generated by Django 5.1.15 on 2026-07-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_rename_tpms_fields_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonnote',
            name='docuseal_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='docuseal_slug',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='docuseal_submitter_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='docuseal_template_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
