# Generated by Django 5.1.15 on 2026-07-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_noteassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notetemplate',
            name='body_template',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='lock_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='require_additional_signatures',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='require_completer_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='template_type',
            field=models.CharField(choices=[('notes', 'Notes'), ('forms', 'Forms'), ('reports', 'Reports')], default='notes', max_length=20),
        ),
    ]
