# Generated by Codex on 2026-09-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_remove_reports_template_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notetemplate',
            name='activity_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='enable_time_change_requests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='include_signatory_credentials',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='show_only_user_collected_data',
            field=models.BooleanField(default=False),
        ),
    ]
