# Generated by Django 5.1.15 on 2026-09-28 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_notetemplate_advanced_options'),
        ('tenants', '0007_organizationtpmsadminid_facility_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteLayoutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_type', models.CharField(choices=[('notes', 'Notes'), ('forms', 'Forms')], default='notes', max_length=20)),
                ('header_enabled', models.BooleanField(default=False)),
                ('header_html', models.TextField(blank=True, default='')),
                ('footer_enabled', models.BooleanField(default=False)),
                ('footer_html', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'template_type'), name='uniq_note_layout_per_org_type')],
            },
        ),
    ]
