# Generated by Django 5.1.15 on 2026-07-14 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_tpms_fields_external'),
        ('tenants', '0002_organization_tpms_admin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Clinical Supervisor'), ('staff', 'RBT / Staff'), ('caregiver', 'Caregiver'), ('reporting', 'Reporting / Audit')], max_length=20)),
                ('permissions', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='tenants.organization')),
            ],
            options={
                'unique_together': {('organization', 'role')},
            },
        ),
    ]
