# Generated by Django 5.1.15 on 2026-07-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rolepermission'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0003_remove_organization_tpms_admin_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_client_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('external_client_id__isnull', False), ('role', 'caregiver')), models.Q(models.Q(('role', 'caregiver'), _negated=True), ('external_client_id__isnull', True)), _connector='OR'), name='caregiver_has_client_link'),
        ),
    ]
