# Generated by Django 5.1.15 on 2026-09-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_mfa_required_usermfa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermfa',
            name='method',
            field=models.CharField(choices=[('totp', 'Authenticator app'), ('email', 'Email')], default='totp', max_length=10),
        ),
        migrations.AddField(
            model_name='usermfa',
            name='otp_code_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usermfa',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermfa',
            name='otp_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermfa',
            name='secret_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
