# Generated by Django 5.1.15 on 2026-07-30 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_clientstaffassignment_organization'),
        ('tenants', '0003_remove_organization_tpms_admin_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorInterventionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('active', 'Active'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('author_name', models.CharField(blank=True, max_length=200)),
                ('effective_date', models.DateField(blank=True, db_index=True, null=True)),
                ('review_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('target_behavior_name', models.CharField(blank=True, max_length=200)),
                ('target_behavior_definition', models.TextField(blank=True)),
                ('baseline_summary', models.TextField(blank=True)),
                ('hypothesized_function', models.CharField(choices=[('escape', 'Escape / Avoidance'), ('attention', 'Attention'), ('tangible', 'Access to Tangible'), ('sensory', 'Automatic / Sensory'), ('multiple', 'Multiple / Combined'), ('unknown', 'Undetermined')], default='unknown', max_length=20)),
                ('function_hypothesis_statement', models.TextField(blank=True)),
                ('antecedent_strategies', models.TextField(blank=True)),
                ('replacement_behaviors', models.TextField(blank=True)),
                ('teaching_procedures', models.TextField(blank=True)),
                ('reinforcement_strategies', models.TextField(blank=True)),
                ('response_procedures', models.TextField(blank=True)),
                ('crisis_plan', models.TextField(blank=True)),
                ('safety_precautions', models.TextField(blank=True)),
                ('data_collection_plan', models.TextField(blank=True)),
                ('generalization_plan', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('activated_by_name', models.CharField(blank=True, max_length=200)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_by_id', models.IntegerField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('archived_by_id', models.IntegerField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('author', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_behavior_plans', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_intervention_plans', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization')),
                ('previous_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_version', to='behavior_plans.behaviorinterventionplan')),
            ],
            options={
                'ordering': ['-version_number', '-created_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='behavior_pl_client__c367dd_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('client',), name='unique_active_bip_per_client'), models.UniqueConstraint(fields=('client', 'version_number'), name='unique_bip_version_number_per_client')],
            },
        ),
    ]
