# Generated by Django 5.1.15 on 2026-07-30 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior_plans', '0001_initial'),
        ('programs', '0024_alter_fadingtemplate_unique_together_and_more'),
        ('tenants', '0003_remove_organization_tpms_admin_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='behaviorinterventionplan',
            name='unique_active_bip_per_client',
        ),
        migrations.RemoveConstraint(
            model_name='behaviorinterventionplan',
            name='unique_bip_version_number_per_client',
        ),
        migrations.RemoveIndex(
            model_name='behaviorinterventionplan',
            name='behavior_pl_client__c367dd_idx',
        ),
        migrations.RemoveField(
            model_name='behaviorinterventionplan',
            name='client',
        ),
        migrations.AddField(
            model_name='behaviorinterventionplan',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_intervention_plans', to='programs.program'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='behaviorinterventionplan',
            index=models.Index(fields=['program', 'status'], name='behavior_pl_program_d78c92_idx'),
        ),
        migrations.AddConstraint(
            model_name='behaviorinterventionplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('program',), name='unique_active_bip_per_program'),
        ),
        migrations.AddConstraint(
            model_name='behaviorinterventionplan',
            constraint=models.UniqueConstraint(fields=('program', 'version_number'), name='unique_bip_version_number_per_program'),
        ),
    ]
