from django.db import models
from shared.models import TenantAwareModel


class Export(TenantAwareModel):
    """
    Audit log for every file generated by the platform.
    Export jobs are dispatched as Celery tasks; this row tracks status and result.
    file_path is a storage-backend key — local media path in dev, S3 key in production.
    """

    class ExportType(models.TextChoices):
        TRIAL_CSV = 'trial_csv', 'Trial Data CSV'
        BEHAVIOR_CSV = 'behavior_csv', 'Behavior Data CSV'
        ABC_CSV = 'abc_csv', 'ABC Data CSV'
        NOTE_PDF = 'note_pdf', 'Note PDF'
        GRAPH_PNG = 'graph_png', 'Graph PNG'
        GRAPH_SVG = 'graph_svg', 'Graph SVG'
        RAW_ZIP = 'raw_zip', 'Raw Data ZIP'

    class Status(models.TextChoices):
        PENDING = 'pending', 'Pending'
        PROCESSING = 'processing', 'Processing'
        COMPLETED = 'completed', 'Completed'
        FAILED = 'failed', 'Failed'

    export_type = models.CharField(max_length=20, choices=ExportType.choices, db_index=True)
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.PENDING, db_index=True)

    # Input parameters — stored so exports can be reproduced and audited
    params = models.JSONField(default=dict)

    # Output
    file_path = models.CharField(max_length=500, blank=True)
    file_size_bytes = models.BigIntegerField(null=True, blank=True)
    row_count = models.IntegerField(null=True, blank=True)
    error_message = models.TextField(blank=True)

    # Lifecycle timestamps
    generated_at = models.DateTimeField(null=True, blank=True)
    expires_at = models.DateTimeField(null=True, blank=True)
    download_count = models.IntegerField(default=0)
    last_downloaded_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        app_label = 'exports'
        ordering = ['-created_at']

    def __str__(self) -> str:
        return f'{self.export_type} [{self.status}] — {self.created_at:%Y-%m-%d}'
