# Generated by Django 5.1.15 on 2026-07-27 07:59, hand-edited to preserve
# existing tpms_admin_id data when converting it to the new one-to-many table.

import django.db.models.deletion
from django.db import migrations, models


def copy_admin_ids_forward(apps, schema_editor):
    Organization = apps.get_model('tenants', 'Organization')
    OrganizationTpmsAdminId = apps.get_model('tenants', 'OrganizationTpmsAdminId')
    for org in Organization.objects.exclude(tpms_admin_id__isnull=True):
        OrganizationTpmsAdminId.objects.create(organization=org, admin_id=org.tpms_admin_id)


def copy_admin_ids_backward(apps, schema_editor):
    Organization = apps.get_model('tenants', 'Organization')
    OrganizationTpmsAdminId = apps.get_model('tenants', 'OrganizationTpmsAdminId')
    for mapping in OrganizationTpmsAdminId.objects.all():
        # Lossy if an org has more than one admin_id — only the last one wins.
        Organization.objects.filter(pk=mapping.organization_id).update(tpms_admin_id=mapping.admin_id)


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_organization_tpms_admin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationTpmsAdminId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.IntegerField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpms_admin_ids', to='tenants.organization')),
            ],
            options={
                'ordering': ['admin_id'],
            },
        ),
        migrations.RunPython(copy_admin_ids_forward, copy_admin_ids_backward),
        migrations.RemoveField(
            model_name='organization',
            name='tpms_admin_id',
        ),
    ]
