# Generated by Django 5.1.15 on 2026-08-25 13:52

from django.db import migrations, models


SEED_STATUSES = [
    {'key': 'waiting',      'label': 'Waiting',      'icon': 'hourglass',      'color': '#94a3b8', 'is_staff_visible': False, 'is_default': True,  'display_order': 0},
    {'key': 'probe',        'label': 'Probe',        'icon': 'clipboard-list', 'color': '#d97706', 'is_staff_visible': True,  'is_default': False, 'display_order': 1},
    {'key': 'acquisition',  'label': 'Acquisition',  'icon': 'graduation-cap', 'color': '#2563eb', 'is_staff_visible': True,  'is_default': False, 'display_order': 2},
    {'key': 'mastered',     'label': 'Mastered',     'icon': 'trophy',         'color': '#7c3aed', 'is_staff_visible': True,  'is_default': False, 'display_order': 3},
    {'key': 'closed',       'label': 'Closed',       'icon': 'check-circle',  'color': '#059669', 'is_staff_visible': False, 'is_default': False, 'display_order': 4},
    {'key': 'hold',         'label': 'Hold',         'icon': 'hand',           'color': '#ea580c', 'is_staff_visible': False, 'is_default': False, 'display_order': 5},
    {'key': 'discontinued', 'label': 'Discontinued', 'icon': 'x-square',      'color': '#dc2626', 'is_staff_visible': False, 'is_default': False, 'display_order': 6},
]


def seed_defaults(apps, schema_editor):
    DefaultTargetStatus = apps.get_model('tenants', 'DefaultTargetStatus')
    for row in SEED_STATUSES:
        DefaultTargetStatus.objects.get_or_create(key=row['key'], defaults=row)


def unseed_defaults(apps, schema_editor):
    DefaultTargetStatus = apps.get_model('tenants', 'DefaultTargetStatus')
    DefaultTargetStatus.objects.filter(key__in=[r['key'] for r in SEED_STATUSES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_remove_organization_tpms_admin_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultTargetStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('icon', models.CharField(default='circle', max_length=30)),
                ('is_staff_visible', models.BooleanField(default=False, help_text='Shown to staff in the session recording view')),
                ('is_default', models.BooleanField(default=False, help_text='Starting status for newly created targets')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.RunPython(seed_defaults, unseed_defaults),
    ]
