# Generated by Codex on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_defaulttargetstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='automatic_logout_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='automatic_logout_minutes',
            field=models.PositiveIntegerField(
                choices=[
                    (540, '9 hours'),
                    (1440, '24 hours'),
                    (10080, '1 week'),
                ],
                default=540,
            ),
        ),
    ]
