# Generated by Codex on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_organization_automatic_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtpmsadminid',
            name='email_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
