# Generated by Django 5.1.15 on 2026-09-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_organizationtpmsadminid_facility_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='integration_platform',
            field=models.CharField(blank=True, choices=[('therapy_pms', 'TherapyPMS')], default='', max_length=30),
        ),
    ]
