# Generated by Django 5.1.15 on 2026-09-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_organization_integration_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='integration_admin_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='integration_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='integration_password_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
