# Generated by Django 5.1.15 on 2026-06-24 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('lesson_type', models.CharField(choices=[('open', 'Open'), ('scheduled', 'Scheduled'), ('appointment_linked', 'Appointment Linked')], default='open', max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MasteryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('rules', models.JSONField(default=dict)),
                ('is_org_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('skill_acquisition', 'Skill Acquisition'), ('behavior_reduction', 'Behavior Reduction'), ('abc_recording', 'ABC Recording')], default='skill_acquisition', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('treatment_area', models.CharField(blank=True, max_length=200)),
                ('tags', models.JSONField(default=list)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PromptingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('levels', models.JSONField(default=list)),
                ('is_org_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('measurement_type', models.CharField(choices=[('trial_by_trial', 'Trial by Trial'), ('frequency', 'Frequency'), ('duration', 'Duration'), ('rate', 'Rate'), ('whole_interval', 'Whole Interval'), ('partial_interval', 'Partial Interval')], default='trial_by_trial', max_length=30)),
                ('sd_text', models.TextField(blank=True, verbose_name='Discriminative Stimulus')),
                ('teaching_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('baseline', 'Baseline'), ('acquisition', 'Acquisition'), ('maintenance', 'Maintenance'), ('teaching', 'Teaching'), ('pending', 'Pending'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('discontinued', 'Discontinued')], db_index=True, default='pending', max_length=20)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_visible_to_staff', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mastery_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets', to='programs.masterytemplate')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='programs.program')),
                ('prompting_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets', to='programs.promptingtemplate')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_programs', to='programs.lesson')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_programs', to='programs.program')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('lesson', 'program')},
            },
        ),
    ]
