# Generated by Django 5.1.15 on 2026-06-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='baseline_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='phase',
            field=models.CharField(blank=True, choices=[('baseline', 'Baseline'), ('teaching', 'Teaching'), ('generalizing', 'Generalizing'), ('maintenance', 'Maintenance'), ('mastered', 'Mastered'), ('on_hold', 'On Hold')], default='teaching', max_length=20),
        ),
    ]
