# Generated by Django 5.1.15 on 2026-06-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_program_baseline_notes_program_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='client',
        ),
        migrations.RemoveField(
            model_name='program',
            name='client',
        ),
        migrations.AddField(
            model_name='lesson',
            name='tpms_client_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='tpms_client_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
