# Generated by Django 5.1.15 on 2026-06-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_remove_lesson_client_remove_program_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_template',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
