# Generated by Django 5.1.15 on 2026-06-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_add_program_is_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('skill_acquisition', 'Skill Acquisition'), ('behavior_reduction', 'Behavior Reduction'), ('abc_recording', 'ABC Recording'), ('telehealth', 'Telehealth')], default='skill_acquisition', max_length=30),
        ),
    ]
