# Generated by Django 5.1.15 on 2026-06-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_add_telehealth_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
