# Generated by Django 5.1.15 on 2026-06-27 10:00

from django.db import migrations, models

STATUS_MAP = {
    'pending':      'waiting',
    'baseline':     'probe',
    'teaching':     'probe',
    'maintenance':  'mastered',
    'completed':    'closed',
    'on_hold':      'hold',
    # acquisition and discontinued stay the same
}


def forwards(apps, schema_editor):
    Target = apps.get_model('programs', 'Target')
    for old, new in STATUS_MAP.items():
        Target.objects.filter(status=old).update(status=new)


def backwards(apps, schema_editor):
    Target = apps.get_model('programs', 'Target')
    for old, new in STATUS_MAP.items():
        Target.objects.filter(status=new).update(status=old)


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_add_settings_models'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='target',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('probe', 'Probe'), ('acquisition', 'Acquisition'), ('mastered', 'Mastered'), ('closed', 'Closed'), ('hold', 'Hold'), ('discontinued', 'Discontinued')], db_index=True, default='waiting', max_length=20),
        ),
    ]
