# Generated by Django 5.1.15 on 2026-06-28 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_rename_target_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='maintenance_episodes_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('interval_type', models.CharField(choices=[('every_n_sessions', 'Every N Sessions'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='every_n_sessions', max_length=20)),
                ('interval_value', models.PositiveIntegerField(default=5, help_text='Number of sessions between maintenance appearances (used with every_n_sessions)')),
                ('episodes', models.PositiveIntegerField(default=4, help_text='Number of successful maintenance episodes before auto-close')),
                ('success_threshold_pct', models.PositiveIntegerField(default=80, help_text='Minimum % correct to count a maintenance episode as successful')),
                ('on_failure', models.CharField(choices=[('back_to_acquisition', 'Back to Acquisition'), ('stay_in_maintenance', 'Stay in Maintenance')], default='back_to_acquisition', max_length=25)),
                ('is_org_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='maintenance_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='programs.maintenanceschedule'),
        ),
        migrations.AddField(
            model_name='target',
            name='maintenance_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets', to='programs.maintenanceschedule'),
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('phases', models.JSONField(default=list)),
                ('is_org_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='workflow_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='programs.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='target',
            name='workflow_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets', to='programs.workflowtemplate'),
        ),
    ]
