# Generated by Django 5.1.15 on 2026-07-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_targetstatus_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdatafield',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='programtag',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='treatmentarea',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
