# Generated by Django 5.1.15 on 2026-07-22 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0019_lessonprogram_organization_and_more'),
        ('tenants', '0002_organization_tpms_admin_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='current_prompt_level_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='target',
            name='fading_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=10),
        ),
        migrations.CreateModel(
            name='FadingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('rules', models.JSONField(default=dict)),
                ('is_org_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='fading_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='programs.fadingtemplate'),
        ),
        migrations.AddField(
            model_name='target',
            name='fading_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets', to='programs.fadingtemplate'),
        ),
        migrations.CreateModel(
            name='TargetPromptLevelChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_level_index', models.PositiveSmallIntegerField()),
                ('to_level_index', models.PositiveSmallIntegerField()),
                ('from_level_label', models.CharField(max_length=100)),
                ('to_level_label', models.CharField(max_length=100)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('auto_fading', 'Automatic — Fading Criteria Met')], max_length=20)),
                ('session_run_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_level_changes', to='programs.target')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
