# Generated by Django 5.1.15 on 2026-07-27 00:00

import apps.programs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0021_remove_target_mastery_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.programs.models._program_upload_path),
        ),
    ]
