# Generated by Django 5.1.15 on 2026-07-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0022_program_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='source_central_program_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
