# Generated by Django 5.1.15 on 2026-07-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0023_program_source_central_program_id'),
        ('tenants', '0002_organization_tpms_admin_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fadingtemplate',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='maintenanceschedule',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='programdatafield',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='programtag',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='promptingtemplate',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='treatmentarea',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='workflowtemplate',
            unique_together={('organization', 'name')},
        ),
    ]
