# Generated by Django 5.1.15 on 2026-08-24 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0028_program_prompting_template_materials'),
        ('tenants', '0003_remove_organization_tpms_admin_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTableView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_key', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('visibility', models.CharField(choices=[('private', 'Only me'), ('everyone', 'All users'), ('roles', 'Specific roles')], default='private', max_length=20)),
                ('roles', models.JSONField(default=list)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
