# Generated by Django 5.1.15 on 2026-08-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0030_target_measurement_timer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='measurement_type',
            field=models.CharField(choices=[('discrete_trial', 'Discrete Trial'), ('duration', 'Duration'), ('rate', 'Rate'), ('task_analysis', 'Task Analysis'), ('set_of_targets', 'Set of Targets'), ('shaping', 'Shaping'), ('instructions', 'Instructions'), ('interval', 'Interval (legacy)')], default='discrete_trial', max_length=30),
        ),
    ]
