# Generated by Django 5.1.15 on 2026-08-29 09:02

import django.db.models.deletion
from django.db import migrations, models


def backfill_sub_item_measurement(apps, schema_editor):
    """Existing steps are all discrete-trial / percent-correct; mirror that into
    the new column and the parent's sub_items JSON."""
    TargetSubItem = apps.get_model('programs', 'TargetSubItem')
    TargetSubItem.objects.filter(measurement='').update(measurement='percent_correct')

    Target = apps.get_model('programs', 'Target')
    for target in Target.objects.exclude(sub_items=[]).only('id', 'sub_items'):
        items = target.sub_items or []
        changed = False
        for item in items:
            if not isinstance(item, dict):
                continue
            item.setdefault('measurement_type', 'discrete_trial')
            item.setdefault('measurement', 'percent_correct')
            item.setdefault('prompting_template_id', None)
            item.setdefault('workflow_template_id', None)
            changed = True
        if changed:
            target.sub_items = items
            target.save(update_fields=['sub_items'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0031_alter_target_measurement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='default_sub_measurement',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='target',
            name='default_sub_measurement_type',
            field=models.CharField(blank=True, choices=[('discrete_trial', 'Discrete Trial'), ('duration', 'Duration')], default='discrete_trial', max_length=20),
        ),
        migrations.AddField(
            model_name='target',
            name='default_sub_prompting_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='programs.promptingtemplate'),
        ),
        migrations.AddField(
            model_name='target',
            name='default_sub_workflow_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='programs.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='targetsubitem',
            name='measurement',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='targetsubitem',
            name='measurement_type',
            field=models.CharField(choices=[('discrete_trial', 'Discrete Trial'), ('duration', 'Duration')], default='discrete_trial', max_length=20),
        ),
        migrations.AddField(
            model_name='targetsubitem',
            name='prompting_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='programs.promptingtemplate'),
        ),
        migrations.AddField(
            model_name='targetsubitem',
            name='workflow_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='programs.workflowtemplate'),
        ),
        migrations.RunPython(backfill_sub_item_measurement, noop_reverse),
    ]
