# Generated by Django 5.1.15 on 2026-08-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0032_target_default_sub_measurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='instructions_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
