# Generated by Django 5.1.15 on 2026-08-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0033_target_instructions_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='interval_pause_on_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='target',
            name='interval_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='target',
            name='interval_sync_with_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='target',
            name='interval_warn_before_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='target',
            name='interval_warn_seconds_before',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='target',
            name='interval_warning_sound',
            field=models.CharField(blank=True, choices=[('buzzer', 'Buzzer'), ('bell', 'Bell'), ('bell_triple', 'Bell Triple Ring'), ('crystal', 'Crystal'), ('cymbal', 'Cymbal'), ('twinkle', 'Twinkle')], default='', max_length=20),
        ),
    ]
