# Generated by Django 5.1.15 on 2026-09-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0039_remove_fading_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='maintenance_schedule',
        ),
        migrations.RemoveField(
            model_name='program',
            name='maintenance_schedule',
        ),
        migrations.DeleteModel(
            name='MaintenanceSchedule',
        ),
    ]
