# Generated by Django 5.1.15 on 2026-09-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0040_remove_target_maintenance_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('skill_acquisition', 'Skill Acquisition'), ('behavior_reduction', 'Behavior Reduction'), ('abc_recording', 'ABC Recording'), ('telehealth', 'Telehealth'), ('instructions_only', 'Instructions Only')], default='skill_acquisition', max_length=30),
        ),
    ]
