# Generated by Django 5.1.15 on 2026-09-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0041_alter_program_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='instructions_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='program',
            name='professional_instructions_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
