# Generated by Codex on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0042_program_instructions_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='custom_field_values',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
