# Generated by Codex on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0043_program_custom_field_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdatafield',
            name='enable_on_all_programs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='programdatafield',
            name='enable_on_program_templates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programdatafield',
            name='program_template_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
