# Generated by Codex on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0044_programdatafield_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdatafield',
            name='show_in_client_sessions',
            field=models.BooleanField(default=False),
        ),
    ]
