# Generated by Codex on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0045_programdatafield_show_in_client_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='therapist_message',
            field=models.TextField(blank=True),
        ),
    ]
