# Generated by Django 5.1.15 on 2026-09-23 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0046_lesson_therapist_message'),
        ('tenants', '0007_organizationtpmsadminid_facility_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramPrototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('skill_acquisition', 'Skill Acquisition'), ('behavior_reduction', 'Behavior Reduction'), ('abc_recording', 'ABC Recording'), ('telehealth', 'Telehealth'), ('instructions_only', 'Instructions Only')], default='skill_acquisition', max_length=30)),
                ('treatment_area', models.CharField(blank=True, max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('hidden_prompt_level_labels', models.JSONField(blank=True, default=list)),
                ('baseline_notes', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('instructions_html', models.TextField(blank=True, default='')),
                ('professional_instructions_html', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization')),
                ('prompting_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='programs.promptingtemplate')),
                ('workflow_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='programs.workflowtemplate')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
