# Generated by Django 5.1.15 on 2026-09-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0047_programprototype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('skill_acquisition', 'Skill Acquisition'), ('behavior_reduction', 'Behavior Reduction'), ('abc_recording', 'ABC Recording'), ('telehealth', 'Telehealth'), ('assessment', 'Assessment'), ('instructions_only', 'Instructions Only')], default='skill_acquisition', max_length=30),
        ),
        migrations.AlterField(
            model_name='programprototype',
            name='category',
            field=models.CharField(choices=[('skill_acquisition', 'Skill Acquisition'), ('behavior_reduction', 'Behavior Reduction'), ('abc_recording', 'ABC Recording'), ('telehealth', 'Telehealth'), ('assessment', 'Assessment'), ('instructions_only', 'Instructions Only')], default='skill_acquisition', max_length=30),
        ),
    ]
