# Generated by Django 5.1.15 on 2026-09-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0048_alter_program_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
