# Generated by Django 5.1.15 on 2026-06-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tpms_admin_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
