# Generated by Django 5.1.15 on 2026-09-24 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_treatment_plan'),
        ('tenants', '0007_organizationtpmsadminid_facility_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlanSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_id', models.IntegerField(db_index=True)),
                ('signer_name', models.CharField(max_length=200)),
                ('signer_role', models.CharField(max_length=50)),
                ('signature_data', models.CharField(max_length=200)),
                ('content_hash', models.CharField(max_length=64)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address_hash', models.CharField(blank=True, max_length=64)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='clients.treatmentplan')),
            ],
            options={
                'ordering': ['signed_at'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'signer_id'), name='one_signature_per_signer_per_plan')],
            },
        ),
    ]
