# Generated by Django 5.1.15 on 2026-06-24 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annotation_type', models.CharField(choices=[('phase_line', 'Phase Line'), ('graph_note', 'Graph Note'), ('phase_range', 'Phase Range')], db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('label', models.CharField(max_length=200)),
                ('color', models.CharField(default='#666666', max_length=7)),
                ('style', models.CharField(choices=[('solid', 'Solid'), ('dashed', 'Dashed'), ('dotted', 'Dotted')], default='solid', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='programs.program')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='programs.target')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
