# Generated by Django 5.1.15 on 2026-09-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_clientannotation'),
        ('programs', '0045_programdatafield_show_in_client_sessions'),
        ('tenants', '0003_remove_organization_tpms_admin_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedInsightGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_client_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('visibility', models.CharField(choices=[('private', 'Only me'), ('everyone', 'All users'), ('roles', 'Specific roles')], default='private', max_length=20)),
                ('roles', models.JSONField(default=list)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_insight_graphs', to='programs.program')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
