# Generated by Django 5.1.15 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_savedinsightgraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedinsightgraph',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
