# Generated by Django 5.1.15 on 2026-09-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_savedinsightgraph_is_default'),
        ('tenants', '0003_remove_organization_tpms_admin_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_client_id', models.PositiveIntegerField(db_index=True)),
                ('assessment_name', models.CharField(db_index=True, max_length=120)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=120)),
                ('metric', models.CharField(blank=True, db_index=True, max_length=120)),
                ('assessed_on', models.DateField(db_index=True)),
                ('score', models.FloatField()),
                ('max_score', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization')),
            ],
            options={
                'ordering': ['assessed_on', 'assessment_name', 'domain', 'metric'],
            },
        ),
    ]
