# Generated by Django 5.1.15 on 2026-07-25 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('skill_acquisition', 'Skill Acquisition'), ('behavior_reduction', 'Behavior Reduction'), ('abc_recording', 'ABC Recording'), ('telehealth', 'Telehealth')], default='skill_acquisition', max_length=30)),
                ('phase', models.CharField(blank=True, choices=[('baseline', 'Baseline'), ('teaching', 'Teaching'), ('generalizing', 'Generalizing'), ('maintenance', 'Maintenance'), ('mastered', 'Mastered'), ('on_hold', 'On Hold')], default='teaching', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('treatment_area', models.CharField(blank=True, max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('objective', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CentralTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('measurement_type', models.CharField(choices=[('discrete_trial', 'Discrete Trial'), ('duration', 'Duration'), ('rate', 'Rate'), ('task_analysis', 'Task Analysis'), ('set_of_targets', 'Set of Targets'), ('shaping', 'Shaping'), ('instructions', 'Instructions')], default='discrete_trial', max_length=30)),
                ('sub_items', models.JSONField(blank=True, default=list)),
                ('sd_text', models.TextField(blank=True, verbose_name='Discriminative Stimulus')),
                ('teaching_instructions', models.TextField(blank=True)),
                ('prompting_levels', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_visible_to_staff', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='central_library.centralprogram')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
