# Generated by Django 5.1.15 on 2026-07-26 23:27

import apps.central_library.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralprogram',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.central_library.models._central_program_upload_path),
        ),
    ]
