# Generated by Codex on 2026-08-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_library', '0003_centralprogramfolder_centralprogram_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('path', models.CharField(blank=True, max_length=240)),
                ('icon', models.CharField(choices=[('bar_chart', 'Bar chart'), ('book', 'Book'), ('building', 'Building'), ('checklist', 'Checklist'), ('clipboard', 'Clipboard'), ('download', 'Download'), ('file_text', 'File text'), ('globe', 'Globe'), ('library', 'Library'), ('settings', 'Settings'), ('shield', 'Shield'), ('users', 'Users')], default='book', max_length=30)),
                ('overview', models.TextField()),
                ('audience', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='central_library.knowledgebasemodule')),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
