# Generated by Django 5.1.15 on 2026-08-27 16:43

import apps.central_library.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_library', '0004_knowledge_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.central_library.models._knowledge_base_import_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('discarded', 'Discarded')], db_index=True, default='draft', max_length=12)),
                ('blocks', models.JSONField(blank=True, default=list)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='central_library.knowledgebasemodule')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
