# Generated by Django 5.1.15 on 2026-09-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_library', '0010_changelogentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralprogram',
            name='category',
            field=models.CharField(choices=[('skill_acquisition', 'Skill Acquisition'), ('behavior_reduction', 'Behavior Reduction'), ('abc_recording', 'ABC Recording'), ('telehealth', 'Telehealth'), ('assessment', 'Assessment')], default='skill_acquisition', max_length=30),
        ),
    ]
