# Generated by Django 5.1.15 on 2026-06-24 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('synced', 'Synced from PM System')], default='manual', max_length=20)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('service_type', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='programs.lesson')),
                ('staff', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SessionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='open', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('program_snapshot', models.JSONField(default=dict)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_run', to='dcm_sessions.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_runs', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_runs', to='programs.lesson')),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sessions', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BehaviorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.PositiveIntegerField(db_index=True)),
                ('target_name', models.CharField(max_length=200)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('frequency_count', models.PositiveIntegerField(default=1)),
                ('severity', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('session_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_events', to='dcm_sessions.sessionrun')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ABCEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('antecedent', models.TextField()),
                ('behavior_description', models.TextField()),
                ('consequence', models.TextField()),
                ('setting', models.CharField(blank=True, max_length=200)),
                ('staff_response', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('session_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abc_events', to='dcm_sessions.sessionrun')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='TrialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.PositiveIntegerField(db_index=True)),
                ('target_name', models.CharField(max_length=200)),
                ('trial_number', models.PositiveIntegerField()),
                ('response_score', models.IntegerField()),
                ('prompt_level_label', models.CharField(max_length=100)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('staff_notes', models.TextField(blank=True)),
                ('session_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_events', to='dcm_sessions.sessionrun')),
            ],
            options={
                'ordering': ['target_id', 'trial_number'],
                'unique_together': {('session_run', 'target_id', 'trial_number')},
            },
        ),
    ]
