# Generated by Django 5.1.15 on 2026-07-23 08:29

import apps.sessions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_sessions', '0006_abcevent_client_event_id_and_more'),
        ('tenants', '0002_organization_tpms_admin_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('target_name', models.CharField(blank=True, max_length=200)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(max_length=500, upload_to=apps.sessions.models._session_media_upload_path)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed')], db_index=True, default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_session_media', to=settings.AUTH_USER_MODEL)),
                ('session_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='dcm_sessions.sessionrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionMediaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('body', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization')),
                ('session_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dcm_sessions.sessionmedia')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
