# Generated by Django 5.1.15 on 2026-07-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_sessions', '0007_sessionmedia_sessionmediacomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrun',
            name='start_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionrun',
            name='start_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
