# Generated by Django 5.1.15 on 2026-08-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_sessions', '0008_sessionrun_start_latitude_sessionrun_start_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialevent',
            name='value_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
