# Generated by Codex on 2026-09-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_abc_client_ids(apps, schema_editor):
    ABCEvent = apps.get_model('dcm_sessions', 'ABCEvent')
    for event in ABCEvent.objects.filter(external_client_id__isnull=True, session_run__isnull=False).select_related('session_run'):
        event.external_client_id = event.session_run.external_client_id
        event.save(update_fields=['external_client_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_sessions', '0009_trialevent_value_seconds'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='abcevent',
            name='session_run',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='abc_events',
                to='dcm_sessions.sessionrun',
            ),
        ),
        migrations.AddField(
            model_name='abcevent',
            name='external_client_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='abcevent',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abcevent',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abcevent',
            name='structured_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(backfill_abc_client_ids, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ABCCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('is_required', models.BooleanField(default=False)),
                ('allow_free_text', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization')),
            ],
            options={
                'ordering': ['display_order', 'label'],
                'unique_together': {('organization', 'key')},
            },
        ),
        migrations.CreateModel(
            name='ABCItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=160)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dcm_sessions.abccategory')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization')),
            ],
            options={
                'ordering': ['display_order', 'label'],
                'unique_together': {('category', 'label')},
            },
        ),
        migrations.AddConstraint(
            model_name='abcevent',
            constraint=models.UniqueConstraint(
                condition=models.Q(session_run__isnull=True, client_event_id__isnull=False),
                fields=('organization', 'external_client_id', 'client_event_id'),
                name='unique_standalone_abc_client_event_id',
            ),
        ),
    ]
