# Generated by Codex on 2026-09-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_sessions', '0010_standalone_abc_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPrototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('message_to_therapist', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.organization')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='sessionrun',
            name='message_to_therapist',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sessionrun',
            name='session_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='sessionrun',
            name='session_prototype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_runs', to='dcm_sessions.sessionprototype'),
        ),
        migrations.AddConstraint(
            model_name='sessionprototype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organization',), name='unique_default_session_prototype_per_org'),
        ),
    ]
