# Generated by Django 5.1.15 on 2026-09-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_sessions', '0011_session_prototypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionrun',
            name='session_prototype',
        ),
        migrations.DeleteModel(
            name='SessionPrototype',
        ),
    ]
