# Generated by Django 5.1.15 on 2026-09-23 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_sessions', '0012_remove_sessionrun_session_prototype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrun',
            name='entry_method',
            field=models.CharField(choices=[('live', 'Recorded live'), ('manual', 'Entered manually')], db_index=True, default='live', max_length=10),
        ),
        migrations.AlterField(
            model_name='sessionrun',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
