# Generated by Django 5.1.15 on 2026-09-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_sessions', '0013_sessionrun_entry_method_alter_sessionrun_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='authorization_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='billable',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cpt_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time_local_raw',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='appointment',
            name='external_admin_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='external_created_at',
            field=models.DateTimeField(blank=True, help_text="The PM system's own created-at timestamp", null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='external_updated_at',
            field=models.DateTimeField(blank=True, help_text="The PM system's own updated-at timestamp", null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='session_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time_local_raw',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Minutes, as reported by the PM system', null=True),
        ),
    ]
