# Generated by Django 5.1.15 on 2026-07-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('session_submitted', 'Session submitted for review'), ('session_approved', 'Session approved'), ('session_rejected', 'Session rejected'), ('target_advanced', 'Target automatically advanced'), ('target_prompt_level_changed', 'Target prompt level automatically changed')], db_index=True, max_length=40),
        ),
    ]
