# Generated by Codex on 2026-09-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_firebasemessagingtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebPushSubscription',
        ),
    ]
