# Generated by Codex on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_rolenotificationpolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('session_submitted', 'Session submitted for review'),
                    ('session_approved', 'Session approved'),
                    ('session_rejected', 'Session rejected'),
                    ('target_advanced', 'Target automatically advanced'),
                    ('target_prompt_level_changed', 'Target prompt level automatically changed'),
                    ('report_review_request', 'Report review request'),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
